version: '3.7'
services:
  superb-api:
    build: ./api
    image: superb/api:latest
    container_name: superb-api
    hostname: superb-api
    stdin_open: true
    tty: true
    working_dir: /var/www
    volumes:
      - ./api:/var/www
    environment:
      - NODE_ENV=development
    networks:
      - backend
    ports:
      - 3001:3000/tcp
    # command: bash -c 'yarn install && tsc && npm start'
    command: cat -

  # superb-website:
  #   build: ./website
  #   image: superb/website:latest
  #   container_name: superb-website
  #   hostname: superb-website
  #   stdin_open: true
  #   tty: true
  #   restart: unless-stopped
  #   working_dir: /var/www
  #   volumes:
  #     - ./website:/var/www
  #   environment:
  #     - NODE_ENV=development
  #     - BROWSER=none
  #   networks:
  #     - backend
  #   ports:
  #     - 3002:3000/tcp
  #   command: bash -c 'yarn install && npm start'

  superb-mongodb:
    image: mongo:4.2.3-bionic
    container_name: superb-mongo
    hostname: superb-mongo
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - 27017:27017/tcp
    networks:
      - backend
    volumes:
      - mongodbdata:/data/db

  superb-rabbitmq:
    image: rabbitmq:3-management
    container_name: superb-rabbitmq
    hostname: superb-rabbitmq
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - 8092:15672/tcp
    networks:
      - backend
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
      - RABBITMQ_DEFAULT_VHOST=local
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq/

networks:
  backend:
    driver: bridge

volumes:
  mongodbdata:
    name: mongodbdata
  rabbitmqdata:
    name: rabbitmqdata
